### ISSUE TITLE
Issue with gift cards

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#127]
Full details and discussion here:
https://wordpress.org/support/topic/issue-with-gift-cards/

**Comment by karmivartio** [comment]
We have same problems with several clients, please increase this priority.

**Comment by jussipvainionpaa** [comment]
> We have same problems with several clients, please increase this priority.

I switched to Markup.fi Paytrail extension. It's free also and it works with some of the biggest gift card extensions: https://markup.fi/products/woocommerce-paytrail/

Just tested and worked fine with PW Gift Cards

**Comment by artio-fi** [comment]
Same problem with **Gift Up** plugin (2.23 version). Only some prices and gift card combinations cause this error.

```
[18-Sep-2024 12:24:02 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setUnitPrice() on null in wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php:1522
Stack trace:
#0 wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1512): Paytrail\WooCommercePaymentGateway\Gateway->fix_rounding_error()
#1 wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1456): Paytrail\WooCommercePaymentGateway\Gateway->get_order_items()
#2 wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1160): Paytrail\WooCommercePaymentGateway\Gateway->set_base_payment_data()
#3 wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): Paytrail\WooCommercePaymentGateway\Gateway->process_payment()

```

**Comment by kotivuori** [comment]
Thanks for reporting @artio-fi. We will take a look at it.
