### ISSUE TITLE
Issue with WooCommerce Product Bundles

### ISSUE THREAD

**Issue by loueranta-paytrail** [paytrail/paytrail-for-woocommerce#70]
A merchant has reported an issue with bundled products when using [WooCommerce Product Bundles](https://woocommerce.com/products/product-bundles/) plugin.

If cart contains bundled products, creating an order fails with following error:

```
2022-11-19T13:10:15+00:00 CRITICAL Uncaught DivisionByZeroError: Division by zero in /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php:1734
Stack trace:
#0 /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1656): Paytrail\WooCommercePaymentGateway\Gateway->get_item_tax_rate(Object(WC_Order_Item_Product), Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1202): Paytrail\WooCommercePaymentGateway\Gateway->create_item(Object(WC_Order_Item_Product), Object(Automattic\WooCommerce\Admin\Overrides\Order))
#2 [internal function]: Paytrail\WooCommercePaymentGateway\Gateway->Paytrail\WooCommercePaymentGateway\{closure}(Object(WC_Order_Item_Product))
#3 /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1201): array_map(Object(Closure), Array)
#4 /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(1176): Paytrail\WooCommercePaymentGateway\Gateway->get_order_items(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#5 /data/wordpress/htdocs/wp-content/plugins/paytrail-for-woocommerce/src/Gateway.php(900): Paytrail\WooCommercePaymentGateway\Gateway->set_base_payment_data(Object(Paytrail\SDK\Request\PaymentRequest), Object(Automattic\WooCommerce\Admin\Overrides\Order))
#6 /data/wordpress/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(982): Paytrail\WooCommercePaymentGateway\Gateway->process_payment(6331)
#7 /data/wordpress/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1206): WC_Checkout->process_order_payment(6331, 'paytrail')
#8 /data/wordpress/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(481): WC_Checkout->process_checkout()
#9 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(307): WC_AJAX::checkout('')
#10 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#11 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#12 /data/wordpress/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(94): do_action('wc_ajax_checkou...')
#13 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(307): WC_AJAX::do_wc_ajax('')
#14 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(false, Array)
#15 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#16 /data/wordpress/htdocs/wordpress/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /data/wordpress/htdocs/wordpress/wp-blog-header.php(19): require_once('/data/wordpress...')
#18 /data/wordpress/htdocs/index.php(4): require('/data/wordpress...')
#19 {main} 
```

**Comment by loueranta-paytrail** [comment]
Was fixed in #71
